name             'wrapper'
maintainer       'Avenue Code LLC'
maintainer_email 'gesteves@avenuecode.com'
license          'All rights reserved'
description      'Installs/Configures wrapper'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.3.7'

depends 'java'
depends 'apt'
depends 'windows'
depends '7-zip'
depends 'ark'
depends 'nodejs'
depends 'runit'
depends 'mongodb'