# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = 'digital_ocean'

  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.hostname = "devops"
    override.ssh.username = "root"
    provider.ssh_key_name = 'Vagrant'
    provider.token = "37b4ff81ff2fbdc6a6eddfbb69c12fd91c4b3bb7f05ab011b6e03d084ecc7d71"
    provider.image = "ubuntu-14-04-x64"
    provider.region = "sfo1"
    provider.size = "1gb"
    provider.backups_enabled = true
    provider.private_networking = true
    provider.ipv6 = true
    provider.setup = true
  end


  config.vm.provision :chef_client do |chef|
    chef.node_name = 'DEVOPS'
    chef.chef_server_url = "https://api.opscode.com/organizations/gesteves-ac"
    chef.validation_key_path = "~/chef-repo/.chef/gesteves-ac-validator.pem"
    chef.validation_client_name = 'gesteves-ac-validator'

    # Remove the chef server nodes
    chef.delete_node = true
    chef.delete_client = true
  end
end
